name: intl_utils
description: intl_utils is a dart library that generates Dart localization code from ARB file. Generated code relies on Intl library.
version: 2.6.1
homepage: https://github.com/localizely/intl_utils

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  analyzer: ">=4.0.0 <6.0.0"
  archive: ^3.0.0
  args: ^2.0.0
  dart_style: ^2.0.0
  http: ^0.13.0
  intl: ^0.18.1
  path: ^1.8.0
  petitparser: ">=4.0.0 <6.0.0"
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.6
  mockito: ^5.1.0
  pedantic: ^1.10.0
  test: ^1.17.10
  lints: ^1.0.0
